<!DOCTYPE html>


<html>
    <?php
        //Creo l'header in cui includo il foglio di stile e setto la pagina del titolo
        include("include/page.php");
        getHeader("Home");
    ?>
    <body>
        <?php
            //La funzione mi aggiunge il menu alla pagina
            getMenu()
        ?>
       <div id="main">
         <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        <p>prova</p>
        </div>
    </body>
</html>
